server:
  port: 8087

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ead-authuser
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
      jdbc:
        log.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
    database: postgresql
#  cores no console
  output:
    ansi:
      enabled: always
#Adiciona log de informação
logging:
  level:
    io.github: trace
    root: info
#    Faz o debug nas requisições web
    org.springframework.web: debug
#    Faz o debug no pacote hibernate, pode ser utilizado em outros pacotes
    org.hibernate: info


api:
  url:
    course: 'http://localhost:8082'